language: java
sudo: required
install: true

jdk:
  # - oraclejdk9
  - oraclejdk11

env:
  - sonarqube: none

cache:
  directories:
  - '$HOME/.m2/repository'
  - '$HOME/.sonar/cache'

notifications:
  email: false

deploy:
  provider: releases
  api_key: ed4e2475867388415dd4ca0426572750e6c084d7
  file: target/sonar-cnes-report.jar
  skip_cleanup: true
  draft: true
