language: java
sudo: required
install: true

jdk:
  # - oraclejdk9
  - oraclejdk11

env:
  - sonarqube: none

cache:
  directories:
  - '$HOME/.m2/repository'
  - '$HOME/.sonar/cache'

notifications:
  email: false

deploy:
  provider: releases
  api_key: 6b95e86a4f410d38f3cc973f6ec6214de5c36a06
  file: target/sonar-cnes-report.jar
  skip_cleanup: true
  draft: true
