language: java
sudo: required
install: true

jdk:
  # - oraclejdk9
  - oraclejdk11

env:
  - sonarqube: none

cache:
  directories:
  - '$HOME/.m2/repository'
  - '$HOME/.sonar/cache'

notifications:
  email: false

deploy:
  provider: releases
  api_key: c4c6db4c1ba8d34d58af5dd7576e389432c84fd7
  file: target/sonar-cnes-report.jar
  skip_cleanup: true
  draft: true
  on:
    branch: master
    repo: ferdiozturk/sonar-cnes-report
