language: java
sudo: required
install: true

services:
  - docker

addons:
  sonarcloud:
    organization: "lequal"

jdk:
  # - oraclejdk9
  - oraclejdk11

env:
  # - sonarqube: none
  - sonarqube: 6.6-alpine
  - sonarqube: 6.7-alpine
  - sonarqube: 6.7.1-alpine
  - sonarqube: 6.7.2-alpine
  - sonarqube: 6.7.3-alpine
  - sonarqube: 6.7.4-alpine
  - sonarqube: 6.7.5-alpine
  - sonarqube: 7.0-alpine
  - sonarqube: 7.1-alpine
  - sonarqube: 7.7-community
  - sonarqube: 7.8-community
  - sonarqube: 7.9-community
  - sonarqube: lts

script:
  - if [ $sonarqube != "none" ]; then
    mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package;
    chmod +x src/test/it/run-test.sh;mvn clean package;
    echo "Starting docker";
    docker run --name sonarqube_${sonarqube} -d -p 127.0.0.1:9000:9000/tcp sonarqube:${sonarqube};
    echo "Inject plugin";
    docker cp target/sonar-cnes-report.jar sonarqube_${sonarqube}:/opt/sonarqube/extensions/plugins/;
    docker exec sonarqube_${sonarqube} chmod 777 /opt/sonarqube/extensions/plugins/sonar-cnes-report.jar;
    docker restart sonarqube_${sonarqube};
    echo "Waiting 5 minutes for SonarQube...";
    sleep 300;
    mvn sonar:sonar -Dsonar.host.url=http://127.0.0.1:9000 -Dsonar.login=admin -Dsonar.password=admin -Dsonar.organization=default-organization -Dsonar.branch.name= ;
    src/test/it/run-test.sh;
    wget "http://localhost:9000/api/cnesreport/report?key=fr.cnes.sonar%3Acnesreport&author=travis-ci&token=noauth";
    else mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar;
    fi

cache:
  directories:
  - '$HOME/.m2/repository'
  - '$HOME/.sonar/cache'

notifications:
  email: false

deploy:
  provider: releases
  api_key:
    secure: e5lFZd6UbvJXevP760iFk9Ck/03B9plqfGX4dd79Hjic8jkeAsBoCkqDdpJpwS/gna8mxmw0MtXuC9EZ9Bu2OQTZDJrUyUa/uHtijDWHegE1SwXhhZPMvhFjWNDMvYI94edmduFt9+yD4CrzVmXJpQv/Y8jGT5LvODnoO3WxmDEv78c+uzECWPU88rQRI08kENEwlIJjEUEmS7uM+Wcz6EcnXWnF8xz1x/kiJwOBekdHbCGZKBBscHxtTwmeU2hKcQt2e9s3uHW3vzHRglNdgnF5tFnUtFCAezBoXbuNNb7MRRmDaLctMKOEjOC2rZIbqUTWYJAewwpYkSbE1gVQLbZLGS5sNj55TxweJYu+4IzOrnNlqzn0GvIcFOnzsZh5yuo+vC27Av7FM5htbq+9BgBDh8Oi7BcyAbCJkud749AtfsAr9ff7l1oXg/QOgE/O23osWAu0oocemJTrf6nlzBtJ/8XoZkPOZTIs2OWnxQLisZ7G9xF/4mAZ63SQRDHJAKryAgDHebDbO4wAKPKvabiLM42JbDLFFC/c7zdSIsf6EPwYEntV4XVXC6z2JadyHWb0xCl30fHbQ5V33G8wb38B7KjNqi4KXVdEtdDbg77zlIKRhHvhbSeRObRw9Ue4oN6/viZPOkqOivR493dqjCt0QM5V6G4DgEy0qvQzTKQlDKarhI2lcfjx5SOlnWzWFHpJARmZE3ZQZY0LBwQHKDHhB8Xrz1Lj5TGUxEWfqWjC0Pa2zJj8j0y5yMQnKjl5BnhDDN6Fr6SB7hbmHBeZCCPFXUPSbPiGXgDyDFedb6GZqxEAdEi4oVB63q3eMC8DaR823ZUUrX9eNP0Qu1NCN/ypIBzMiyMxq+1HCDN7SnOcLcULCQcwGVIlyuuMRo87X5vHQ0TKMs/AUyuYQmXVnMUR/ZWKGhYYSUc/QQCynxE2cr0wa7VKRDXJGEpeyvcxU+g7R9uvuYCsufJEhwayODFngUEO5c+63kxRRstOHg6DMYWxVgwea+NPKUHAO1qRPPx9xmxtSU2ZExvpjvQcUBREXPT6dJWwQYUYjQZvaBJOYAGyBsJIzlCt6ax+RZoen/ZotRgXragLm1eCP9C0nfILd5tEOo8ntq12JjWT8mQYGYJMeLNqMySp3Kt9paclhJKPamzlNKfk6Hs04qZAmmU+IL2ZUB0lzooOrpnOfAeo8jBtsVqfAUJnpR7vnmyFJDd06NGKrPR0E+c1U+fnkF3qPE3vPeWwxFWNmipImtWqa1vK5pYNMY8Ojcr9IuZzW22YRyoj10cDZKW7vAtFbziuwbvIIWaRTnSELtSccVm82ZTGae0mzll/H8lWnzCqOL1/CQxJNTqMSvVSfQnFobF8UoHUr8CKgQKA35A9lOkxMPuDmYwiAg7L0nIn1ORZBOKiDPG1AQOw3Xm/QYsFnx7AZ+FC+ODJJjBvNIt6/28msdepgqs2CRA1oODw4xSbagCOZMbHoxlJ8Z1ryMZ3BsCkmEDObvMRB09UIT58H/ZkDj1tkW1HWKan1JI3zTS31pTBjPomAIPtTiGyi1LSlj0Zs0p4sONMepU/oyKOF43Jzuvsm/T5/w==
    file: target/sonar-cnes-report.jar
  skip_cleanup: true
  draft: true
  on:
    branch: master
